language: php
dist: bionic

notifications:
  email:
    recipients:
      - tomas.mikkelsen@aoe.com
      - stefan.rotsch@aoe.com
    on_success: never
    on_failure: never

before_install:
  # turn off XDebug for speed up
  - phpenv config-rm xdebug.ini || return 0

addons:
  apt:
    packages:
      - parallel
  sonarcloud:
    organization: "aoe-crawler"
    branches:
      - master
      - sonarqube
php:
  - '7.2'
  - '7.3'
  - '7.4'

env:
  # tested TYPO3 version
  - TYPO3_VERSION=^9.5
  - TYPO3_VERSION=^10.4
  - TYPO3_VERSION=dev-master

services:
  - mysql
  - docker

jdk:
  - oraclejdk8

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - wget https://getcomposer.org/download/1.10.9/composer.phar
  - mv composer.phar composer
  - chmod +x composer
  # Installs nimut/typo3-complete
  - php composer require --dev nimut/typo3-complete=$TYPO3_VERSION
  - export "TYPO3_PATH_WEB"=$PWD/.Build/Web;
  # Locating UnitTests.xml

script:
  # run tests by default
  # unit tests
  - composer --version
  -  php composer --version

jobs:
  fast_finish: true
  allow_failures:
    - php: 7.3
    - php: 7.4
    - env: TYPO3_VERSION=dev-master
